use_frameworks!

target 'secp256k1_Example' do
  pod 'secp256k1.swift', :path => '../'

  target 'secp256k1_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end
